[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"
bright_foreground = "#4c4f69"
dim_foreground = "#8c8fa1"

[colors.cursor]
text = "#eff1f5"
cursor = "#dc8a78"

[colors.vi_mode_cursor]
text = "#eff1f5"
cursor = "#7287fd"

[colors.selection]
text = "#4c4f69"
background = "#bcc0cc"

[colors.normal]
black   = "#5c5f77"
red     = "#d20f39"
green   = "#40a02b"
yellow  = "#df8e1d"
blue    = "#1e66f5"
magenta = "#ea76cb"
cyan    = "#179299"
white   = "#acb0be"

[colors.bright]
black   = "#6c6f85"
red     = "#d20f39"
green   = "#40a02b"
yellow  = "#df8e1d"
blue    = "#1e66f5"
magenta = "#ea76cb"
cyan    = "#179299"
white   = "#bcc0cc"
