[colors.primary]
background = "#ffffff"
foreground = "#24292f"
bright_foreground = "#1f2328"
dim_foreground = "#57606a"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#ddf4ff"

[colors.normal]
black   = "#24292f"
red     = "#cf222e"
green   = "#1a7f37"
yellow  = "#9a6700"
blue    = "#0969da"
magenta = "#8250df"
cyan    = "#1b7c83"
white   = "#6e7781"

[colors.bright]
black   = "#57606a"
red     = "#a40e26"
green   = "#116329"
yellow  = "#7d4e00"
blue    = "#0550ae"
magenta = "#6639ba"
cyan    = "#3192aa"
white   = "#8c959f"
