# Gruvbox Dark theme for yazi
[manager]
cwd = { fg = "#d79921" }
hovered         = { fg = "#282828", bg = "#d79921" }
preview_hovered = { underline = true }
find_keyword  = { fg = "#d79921", italic = true }
find_position = { fg = "#d65d0e", bg = "reset", italic = true }
marker_selected = { fg = "#98971a", bg = "#98971a" }
marker_copied   = { fg = "#d79921", bg = "#d79921" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }
tab_active   = { fg = "#282828", bg = "#d79921" }
tab_inactive = { fg = "#d4be98", bg = "#3c3836" }
tab_width    = 1
count_copied   = { fg = "#282828", bg = "#98971a" }
count_cut      = { fg = "#282828", bg = "#fb4934" }
count_selected = { fg = "#282828", bg = "#d79921" }
border_symbol = "│"
border_style  = { fg = "#504945" }
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#504945", bg = "#504945" }
mode_normal = { fg = "#282828", bg = "#d79921", bold = true }
mode_select = { fg = "#282828", bg = "#98971a", bold = true }
mode_unset  = { fg = "#282828", bg = "#b16286", bold = true }
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#d79921", bg = "#3c3836" }
progress_error  = { fg = "#fb4934", bg = "#3c3836" }
permissions_t = { fg = "#83a598" }
permissions_r = { fg = "#fabd2f" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#b8bb26" }
permissions_s = { fg = "#504945" }

[input]
border   = { fg = "#d79921" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#d79921" }
active   = { fg = "#d65d0e" }
inactive = {}

[tasks]
border  = { fg = "#d79921" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#3c3836" }
cand            = { fg = "#83a598" }
rest            = { fg = "#928374" }
desc            = { fg = "#d65d0e" }
separator       = "  "
separator_style = { fg = "#665c54" }

[help]
on      = { fg = "#83a598" }
exec    = { fg = "#d65d0e" }
desc    = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer  = { fg = "#3c3836", bg = "#d4be98" }

[filetype]
rules = [
    { mime = "image/*", fg = "#d79921" },
    { mime = "video/*", fg = "#b16286" },
    { mime = "audio/*", fg = "#b16286" },
    { mime = "application/zip",    fg = "#fb4934" },
    { mime = "application/gzip",   fg = "#fb4934" },
    { mime = "application/x-tar",  fg = "#fb4934" },
    { mime = "application/x-bzip", fg = "#fb4934" },
    { mime = "application/x-bzip2",fg = "#fb4934" },
    { mime = "application/x-7z-compressed", fg = "#fb4934" },
    { mime = "application/x-rar",  fg = "#fb4934" },
    { mime = "application/pdf",    fg = "#fabd2f" },
    { mime = "application/doc",    fg = "#83a598" },
    { mime = "application/rtf",    fg = "#83a598" },
    { name = "*", is = "exec", fg = "#b8bb26" },
    { name = "*/", fg = "#83a598" },
]
